Feature: TM Sandbox API Response Validation
  
  As a user, I want to validate specific fields in the response generated by the TM Sandbox API after processing an HTTP GET request.

  @Scenario1 @FieldValidationPerStep
  Scenario Outline: Validate fields in API response (Per Step)
  	Given the API endpoint with code: "<endpoint>" is retrieved from the application configuration
    When an HTTP GET request is sent to the API endpoint
    Then the response should be received and parsed
#
    # Each field is validated individually in separate steps. If any validation fails, subsequent validations will be skipped.
    #And the value of the field: "Name" in the response should be "<expected_name_value>"
    #And the value of the field: "CanRelist" in the response should be "<expected_canrelist_value>"
    #And the value of the field: "Description" in the response should be "<expected_description_value>" on object: "Promotions" having "Name" as "Gallery"

    Examples: 
      | endpoint           | expected_name_value | expected_canrelist_value | expected_description_value |
      | endpoint-tmsandbox | Carbon credits      | true                     | Good position in category  |

  #@Scenario2 @FieldValidationPerFieldType
  #Scenario Outline: Validate fields in API response (Per Field Type)
    #When an HTTP GET request is sent to the API endpoint
    #Then the response should be received and parsed
#
    # The fields are validated separately based on their property types (simple fields and fields within a complex object).
    #And the following fields are validated in the response:
      #| property  | expected_value               |
      #| Name      | "<expected_name_value>"      |
      #| CanRelist | "<expected_canrelist_value>" |
    #And the following fields are validated in the response:
      #| object     | property_helper | property_helper_value | property    | expected_value                 |
      #| Promotions | Name            | Gallery               | Description | "<expected_description_value>" |
#
    #Examples: 
      #| endpoint           | expected_name_value | expected_canrelist_value | expected_description_value |
      #| endpoint-tmsandbox | Carbon credits      | true                     | Good position in category  |
#
  #@Scenario3 @FieldValidationInOneStep
  #Scenario Outline: Validate fields in API response (In One Step)
    #When an HTTP GET request is sent to the API endpoint
    #Then the response should be received and parsed
#
    # All fields, including both simple fields and fields within a complex object, are validated together in one step.
    #And the following fields are validated in the response:
      #| object     | property_helper | property_helper_value | property    | expected_value                 |
      #|            |                 |                       | Name        | "<expected_name_value>"        |
      #|            |                 |                       | CanRelist   | "<expected_canrelist_value>"   |
      #| Promotions | Name            | Gallery               | Description | "<expected_description_value>" |
#
    #Examples: 
      #| endpoint           | expected_name_value | expected_canrelist_value | expected_description_value |
      #| endpoint-tmsandbox | Carbon credits      | true                     | Good position in category  |
